siteTitle: Super Tabs
description: Swipeable tabs for Ionic apps
repo: https://github.com/zyra/ionic-super-tabs
outDir: docs
baseUrl: https://zyra.github.io/ionic-super-tabs

pagePatterns:
- name: '{{ index .PathMatches 0 1 }}'
  sourceGlob: core/src/**/readme.md
  pattern: '([a-z-]+)/readme.md$'
  path: '/components/{{ index .PathMatches 0 1 }}'
  editOnGithub: true
  addToMenu: true
  menuGroup: components

pages:
- name: home
  title: Super Tabs - Swipeable tabs for Ionic apps
  path: /
  source: README.md
  editOnGithub: true

menuItems:
- title: Getting started
  name: getting-started
  group: true
  items:
  - title: Introduction
    link: /

- title: Components
  name: components
  group: true
