siteTitle: Super Tabs
description: Swipeable tabs for Ionic apps
repo: https://github.com/zyra/ionic-super-tabs
outDir: docs
baseUrl: https://zyra.github.io/ionic-super-tabs/

pagePatterns:
- name: '{{ index .PathMatches 0 1 }}'
  sourceGlob: core/src/**/readme.md
  pattern: '([a-z-]+)/readme.md$'
  path: 'components/{{ index .PathMatches 0 1 }}'
  editOnGithub: true
  addToMenu: true
  menuGroup: components

pages:
- name: home
  title: Super Tabs - Swipeable tabs for Ionic apps
  path: /
  source: doc-pages/home.md
  editOnGithub: true
- name: config
  title: Configuration
  path: configuration
  source: doc-pages/configuration.md
  editOnGithub: true
- name: install-ng
  title: Getting started with Angular
  path: getting-started/angular
  source: doc-pages/getting-started/angular.md
  editOnGithub: true
- name: usage-ng
  title: Angular Usage Guide
  path: usage/angular
  source: doc-pages/usage/angular.md
  editOnGithub: true


menuItems:
- title: Getting started
  name: getting-started
  group: true
  items:
  - title: Introduction
  - title: Angular
    link: getting-started/angular
#  - title: JavaScript
#    link: getting-started/javascript

- title: Configuration
  link: configuration

- title: Usage guide
  name: usage-guide
  group: true
  items:
  - title: Angular
    link: usage/angular

- title: Components
  name: components
  group: true

templates:
- name: base
  source: .doctemplate
