---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
- name: Install node modules
  image: node:12-alpine
  commands:
  - npm install
  - npx lerna bootstrap

- name: Build
  image: node:12-alpine
  commands:
  - npm run build

- name: Publish core package
  image: plugins/npm
  when:
    event:
    - tag
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email
    folder: core

- name: Publish angular package
  image: plugins/npm
  when:
    event:
    - tag
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email
    folder: angular/dist

- name: Generate docs
  image: harbor.zyra.ca/public/zmdocs:v1.0.1
  when:
    branch:
      - master
  commands:
    - zmdoc g

- name: Publish docs
  image: plugins/gh-pages
  when:
    branch:
      - master
  settings:
    username:
      from_secret: gh_user
    password:
      from_secret: gh_token
    pages_directory: docs

#- name: Update example project
#  image: plugins/downstream
#  settings:
#    server: https://drone.zyra.ca
#    token:
#      from_secret: drone_token
#    repositories:
#    - zyra/ionic-super-tabs-example
#    fork: true

---
kind: signature
hmac: 50d6fc56ae57ced338ce709c7cd18bab6d324b54a69be6d3615c3d0cb01bbe21

...
