---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
- name: Install node modules
  image: node:12-alpine
  commands:
  - npm install
  - npx lerna bootstrap

- name: Build
  image: node:12-alpine
  commands:
  - npm run build

- name: Publish
  image: node:12
  when:
    event:
    - tag
  environment:
    NPM_TOKEN:
      from_secret: npm_token
  commands:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  - cd core && npm publish && cd ../
  - cd angular/dist && npm publish

#- name: Update example project
#  image: plugins/downstream
#  settings:
#    server: https://drone.zyra.ca
#    token:
#      from_secret: drone_token
#    repositories:
#    - zyra/ionic-super-tabs-example
#    fork: true

---
kind: signature
hmac: 3578449e61b5be64bccc01be1a252a30b02b690912164d5fc93ebdf70afcd8ea

...
